# format = '''
# [â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€](bold green)
# [â”‚](bold green)$directory$rust$package
# [â””â”€](bold green) '''

# Use custom format
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[âœ](bold red)' 
# use_symbol_for_status = true

[directory]
truncation_length = 5 
truncation_symbol = ".../"
truncate_to_repo=false

[container]
format = '[ğŸ‹ \[PERCEPTION_LOCOMOTION\]](bold blue dimmed) '
# format = '[ğŸ‹ $info](green)'
disabled = false
